In [ ]:
import pandas as pd
import numpy as np

In [49]:

GDP_df = pd.read_csv('cbs_GDP.csv', sep=';')
GDP_df = GDP_df.drop(columns='Periods')
GDP_df = GDP_df.transpose()

# renaming the columns by creating a new dataframe
headers = GDP_df.iloc[0]
new_GDP = pd.DataFrame(GDP_df.values[1:], columns=headers) 

# renaming the provinces to match the other data set
new_GDP = new_GDP.rename(columns={
    "The Netherlands": "the Netherlands",
    "Frysl√¢n (PV)": "Friesland (PV)",
    "Noord-Holland (PV)": "North Holland (PV)",
    "Zuid-Holland (PV)": "South Holland (PV)",
    "Noord-Brabant (PV)": "North Brabant (PV)"
})

# Set the 'Regions' column
new_GDP.insert(0, 'Regions', ["GDP (market prices) (million euros)", "GDP per capita (euros)"], True)


# Create private and shared cost lists
private = ["Car = 0.39", "Bike = 0.0373"]
shared = ["Car = 0.3", "Bike = 0.1176"]

# Create new columns and assign values
new_GDP["Cost per km for privately owned vehicle in ct."] = private
new_GDP["Cost per km for shared vehicle (Hely) in ct."] = shared

# Rearrange the columns
cols = ['Cost per km for privately owned vehicle in ct.', 'Cost per km for shared vehicle (Hely) in ct.', 'Regions'] + \
       [col for col in new_GDP if col != 'Regions' and col not in ['Cost per km for privately owned vehicle in ct.', 'Cost per km for shared vehicle (Hely) in ct.']]

new_GDP = new_GDP[cols]

display(new_GDP)

Regions,Cost per km for privately owned vehicle in ct.,Cost per km for shared vehicle (Hely) in ct.,Regions,the Netherlands,Groningen (PV),Friesland (PV),Drenthe (PV),Overijssel (PV),Flevoland (PV),Gelderland (PV),Utrecht (PV),North Holland (PV),South Holland (PV),Zeeland (PV),North Brabant (PV),Limburg (PV)
0,Car = 0.39,Car = 0.3,GDP (market prices) (million euros),958549,32566,25490,18434,53172,17303,95416,88660,204169,200451,17839,142912,54104
1,Bike = 0.0373,Bike = 0.1176,GDP per capita (euros),54671,55332,39052,37146,45476,40100,45360,64928,70424,53597,46205,55319,48433

In [35]:
#price per km
cost_private = {
  "Car" : "0.39",
  "Bike" : "0.0373" 
}

cost_shared = {
    "Car" : 0.3,
    "Bike" : 0.1176 
}

# Cost data frame
Cost_df = pd.DataFrame.from_dict({"Cost per km for privately owned vehicle in ct.": cost_private,
                                  "Cost per km for shared vehicle (Hely) in ct.": cost_shared}, orient='index')
Cost_df = Cost_df.transpose()

# Display the Cost_df
display(Cost_df)

,Cost per km for privately owned vehicle in ct.,Cost per km for shared vehicle (Hely) in ct.
Car,0.39,0.3
Bike,0.0373,0.1176