In [4]:
import pandas as pd
import numpy as np
import statistics

In [7]:
GDP = pd.read_csv("cbs_GDP.csv")

display(GDP)
# #price per km
# cost_private = {
#   "Car" : "0.39",
#   "Bike" : "0.0373",
#   "Walking" : "NaN", 
# }

# cost_shared = {
#     "Car" : 0.3,
#     "Bike" : 0.1176, 
#     "Walking" : "NaN"
# }

# cost_df = (cost_private, columns = ["Cost per km Private"])
# cost_df ["Cost per km Shared"] = cost_shared
# cost_df ["GDP per Region"] =

   Periods;"Regions";"GDP (market prices) (million euros)";"GDP per capita (euros)"
0       2022*;"The Netherlands";"  958549";"   54671"
1        2022*;"Groningen (PV)";"   32566";"   55332"
2          2022*;"Fryslân (PV)";"   25490";"   39052"
3          2022*;"Drenthe (PV)";"   18434";"   37146"
4       2022*;"Overijssel (PV)";"   53172";"   45476"
5        2022*;"Flevoland (PV)";"   17303";"   40100"
6       2022*;"Gelderland (PV)";"   95416";"   45360"
7          2022*;"Utrecht (PV)";"   88660";"   64928"
8    2022*;"Noord-Holland (PV)";"  204169";"   70424"
9     2022*;"Zuid-Holland (PV)";"  200451";"   53597"
10         2022*;"Zeeland (PV)";"   17839";"   46205"
11   2022*;"Noord-Brabant (PV)";"  142912";"   55319"
12         2022*;"Limburg (PV)";"   54104";"   48433"